artifact_uri: file:///C:/Users/Lab/PycharmProjects/MachineLearningCourse/machine_learning_course/mlruns/0/3caa7240613349e2b753408d4e8f33da/artifacts
end_time: 1638279271807
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3caa7240613349e2b753408d4e8f33da
run_uuid: 3caa7240613349e2b753408d4e8f33da
source_name: ''
source_type: 4
source_version: ''
start_time: 1638279268792
status: 3
tags: []
user_id: Lab
